config/routes.rb
Rails.application.routes.draw do
  # devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :events, only: [:index, :create] do
    resources :favourites, only: [:create, :destroy]
  end

  devise_for :users,
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  get 'users/dashboard', to: 'users#dashboard'


end

app/views/shared/_carousel.html.erb
<div id="carouselExampleControls" class="carousel slide" data-pause="false" data-ride="carousel">
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img class="dimension" src="https://res.cloudinary.com/rahulsuvarna18/image/upload/v1566353796/action-active-audience-2466341_lmebc6.jpg" alt="First slide">

    </div>
    <div class="carousel-item">
      <img class="dimension" src="https://res.cloudinary.com/rahulsuvarna18/image/upload/v1566353757/audience-band-celebration-1190298_cklxuh.jpg" alt="Second slide">

    </div>
    <div class="carousel-item">
      <img class="dimension" src="https://res.cloudinary.com/rahulsuvarna18/image/upload/v1566353769/audience-band-celebration-2034851_fdxqq2.jpg" alt="Third slide">

    </div>
    <div class="carousel-item">
      <img class="dimension" src="https://res.cloudinary.com/rahulsuvarna18/image/upload/v1566353783/audience-band-celebration-1983046_eyplfo.jpg" alt="Fourth slide">

    </div>
    <div class="carousel-item">
      <img class="dimension" src="https://res.cloudinary.com/rahulsuvarna18/image/upload/v1566354501/audience-backlit-band-154147_vwl9ve.jpg" alt="Fifth slide">

    </div>

  </div>
</div>

app/views/shared/_categories.html.erb
<%= simple_form_for :index, url: events_path, method: :get do |f| %>
<input type="hidden" name="location" value='<%=params[:location]%>'>
<div class="card" style="height:100vh">
    <article class="card-group-item">
    <header class="card-header">
      <h6 class="title">Dates </h6>
    </header>
    <div class="filter-content">
      <div class="card-body">
      <div class="form-group">
        <label>Start</label>
        <input type="date" class="form-control" name="start_date">
      </div>
      <div class="form-group">
        <label>End</label>
        <input type="date" class="form-control" name="end_date">
      </div>
 <!--      <div class="row">
        <button name="button" type="submit" class="btn btn-flat">
          <i class="fas fa-search"></i> Filter
        </button>
      </div> -->

      </div> <!-- card-body.// -->
    </div>
  </article> <!-- card-group-item.// -->

  <article class="card-group-item">
    <header class="card-header">
      <h6 class="title">Select a category </h6>
    </header>
    <div class="filter-content">
      <div class="card-body">

        <div id="scrollingTable" style="overflow-y:scroll">

          <% @categories.each do |category| %>
            <% count = 0 %>
            <% @events.each do |event| %>
              <% if event[:category] == category[:name] %>
                <% count += 1 %>
              <% end %>
            <% end %>
            <% if count > 5 %>
              <div class="custom-control custom-checkbox">
                <span class="float-right badge badge-light round">
                  <%= count %>
                  </span>
                  <input type="checkbox" class="custom-control-input" id='<%=category[:id]%>' name="categories" value='<%=category[:id]%>'>
                  <label class="custom-control-label" for='<%=category[:id]%>'><%=category[:name]%></label>
              </div> <!-- form-check.// -->
            <% end %>
          <% end %>
        </div>


      </div> <!-- card-body.// -->
    </div>
  </article> <!-- card-group-item.// -->
    <div class="row justify-content-center mt-4">
      <button name="button" type="submit" class="btn btn-primary" value="params[:location]"> Reset filter
      </button>
    </div>

</div> <!-- card.// -->
<% end %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_loader.html.erb
<main>
   <div class="dank-ass-loader">
      <div class="row">
         <div class="arrow up outer outer-18"></div>
         <div class="arrow down outer outer-17"></div>
         <div class="arrow up outer outer-16"></div>
         <div class="arrow down outer outer-15"></div>
         <div class="arrow up outer outer-14"></div>
      </div>
      <div class="row">
         <div class="arrow up outer outer-1"></div>
         <div class="arrow down outer outer-2"></div>
         <div class="arrow up inner inner-6"></div>
         <div class="arrow down inner inner-5"></div>
         <div class="arrow up inner inner-4"></div>
         <div class="arrow down outer outer-13"></div>
         <div class="arrow up outer outer-12"></div>
      </div>
      <div class="row">
         <div class="arrow down outer outer-3"></div>
         <div class="arrow up outer outer-4"></div>
         <div class="arrow down inner inner-1"></div>
         <div class="arrow up inner inner-2"></div>
         <div class="arrow down inner inner-3"></div>
         <div class="arrow up outer outer-11"></div>
         <div class="arrow down outer outer-10"></div>
      </div>
      <div class="row">
         <div class="arrow down outer outer-5"></div>
         <div class="arrow up outer outer-6"></div>
         <div class="arrow down outer outer-7"></div>
         <div class="arrow up outer outer-8"></div>
         <div class="arrow down outer outer-9"></div>
      </div>
      <p class="text-white mt-3" id="typed" style="min-height: 30px;"></p>
   </div>
</main>

app/views/shared/_logo.html.erb
<svg class="specialtext" xmlns="http://www.w3.org/2000/svg" version="1.1" viewBox="0 0 750 200" preserveAspectRatio="xMidYMid meet" style="height:150%">
  <defs>
    <filter id="texteffect">
      <feGaussianBlur in="SourceGraphic" stdDeviation="4"></feGaussianBlur>
      <feComponentTransfer>
        <feFuncA type="linear" slope="1.5" intercept="0"></feFuncA>
      </feComponentTransfer>
      <feComposite result="outer" in2="SourceGraphic" operator="out"></feComposite>
      <feGaussianBlur result="pre-inner" in="SourceGraphic" stdDeviation="2"></feGaussianBlur>
      <feComposite in="SourceGraphic" in2="pre-inner" operator="out"></feComposite>
      <feComponentTransfer result="inner">
        <feFuncA type="linear" slope="7.5" intercept="0"></feFuncA>
      </feComponentTransfer>
      <feMerge>
        <feMergeNode in="outer"></feMergeNode>
        <feMergeNode in="inner"></feMergeNode>
      </feMerge>
      <feGaussianBlur stdDeviation="1"></feGaussianBlur>
    </filter>
    <linearGradient id="gradient" color-interpolation="sRGB" spreadMethod="repeat" x1="0" x2="0.5" y1="0.02" y2="0">
      <stop stop-color="#EE6631" offset="0%"></stop>
      <stop stop-color="#fafcfc" offset="33%"></stop>
      <stop stop-color="#f2a415" offset="66%"></stop>
      <stop stop-color="#EE6631" offset="100%"></stop>
    </linearGradient>
    <mask id="textMask">
      <g filter="url(#texteffect)">
        <rect x="10" y="20" width="730" height="10" fill="#fff"></rect>
        <rect x="10" y="170" width="730" height="10" fill="#fff"></rect>
        <text id="text" x="375" y="150" text-anchor="middle" fill="#fff">FireEvents</text>
      </g>
    </mask>
  </defs>
  <rect id="fill" mask="url(#textMask)" fill="url(#gradient)" x="0" y="0" width="4000" height="200"></rect>
</svg>

app/views/shared/_mapbar.html.erb
<div class="center-container">
  <%= simple_form_for :index, url: events_path, method: :get do |f| %>
    <div class="mapbar">
      <%= link_to "/", id: "navbar-brand" do %>
        <%= image_tag "https://emojipedia-us.s3.dualstack.us-west-1.amazonaws.com/thumbs/160/facebook/92/fire_1f525.png" %>
        <% end %>

      <div class="search-form-control form-group col-3" style="
    padding-left: 0px; margin-bottom:0px; border-radius:10px">
      <%= text_field_tag :location, params[:location].titleize, class: "form-control string required index-search" %>
      </div>
      <div class="dropdown">
        <button class="btn btn-yellow dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Start date
        </button>
        <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
          <input type="date" class="dropdown-item" name="start_date">
        </div>
      </div>
      <div class="dropdown">
        <button class="btn btn-yellow dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          End date
        </button>
        <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
          <input type="date" class="dropdown-item" name="end_date">
        </div>
      </div>
      <div class="dropdown">
        <button class="btn btn-yellow dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" style="width: 100%">
          Category
        </button>
        <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
          <% @categories.each do |category| %>
            <div class="dropdown-item">
              <div class="custom-control custom-checkbox">
                <input type="checkbox" class="custom-control-input" id='<%=category[:id]%>' name="categories" value='<%=category[:id]%>'>
                <label class="custom-control-label" for='<%=category[:id]%>'><%=category[:name]%></label>
              </div>
            </div>
          <% end %>
        </div>
      </div>
      <div class="button">
        <button name="button" id="home-search" type="submit" class="btn btn-red">          <i class="fas fa-search"></i> Search
        </button>
      </div>
  <% end %>


    <%= simple_form_for :index, url: events_path, method: :get do |f| %>
      <div class="button">
        <button name="location" type="submit" class="btn btn-yellow" value="<%=params[:location]%>"> Reset filters
        </button>
      </div>
    <%end%>

  <div class="avatar">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item dropdown">
          <% if current_user %>
            <% avatar_url = cl_image_path(current_user.avatar) || "http://placehold.it/30x30" %>
            <%= image_tag avatar_url, class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <% end %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <% if current_user %>
          <p class="dropdown-item">Welcome, <%= current_user.first_name%></p>
          <% end %>
            <%= link_to "Events", events_path, class: "dropdown-item" %>
            <%= link_to "Favourites", users_dashboard_path, class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>

  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon fixed-top mt-1">
  <%= link_to "/", class: "navbar-brand" do %>
    <%= image_tag "https://emojipedia-us.s3.dualstack.us-west-1.amazonaws.com/thumbs/160/facebook/92/fire_1f525.png"%>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item dropdown">
          <% if current_user %>
            <% avatar_url = cl_image_path(current_user.avatar) || "http://placehold.it/30x30" %>
            <%= image_tag avatar_url, class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <% end %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <% if current_user %>
          <p class="dropdown-item">Welcome, <%= current_user.first_name%> <%= current_user.last_name%></p>
          <% end %>
            <%= link_to "Events", events_path, class: "dropdown-item" %>
            <%= link_to "Favourites", users_dashboard_path, class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/shared/_search.html.erb
<div class="search-bar">
<%= simple_form_for :index, url: events_path, method: :get do |f| %>
  <div class="home-search-form-control form-group">
    <input class="form-control string required" type="text" name="location"  id="search_query" placeholder="Discover a location" />
    <button name="button" type="submit" class="btn" id="home-search">
    <i class="fas fa-search-location"></i>
    </button>
  </div>
<% end %>
</div>

app/views/shared/_solid-navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon" style="background-color: #212121;">
  <%= link_to "/", class: "navbar-brand" do %>
    <%= image_tag "https://emojipedia-us.s3.dualstack.us-west-1.amazonaws.com/thumbs/160/facebook/92/fire_1f525.png" %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item dropdown">
          <% if current_user %>
            <% avatar_url = cl_image_path(current_user.avatar) || "http://placehold.it/30x30" %>
            <%= image_tag avatar_url, class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <% end %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <% if current_user %>
          <p class="dropdown-item">Welcome, <%= current_user.first_name%> <%= current_user.last_name%></p>
          <% end %>
            <%= link_to "Events", events_path, class: "dropdown-item" %>
            <%= link_to "Favourites", users_dashboard_path, class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>