config/routes.rb
Rails.application.routes.draw do
  # devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :events, only: [:index, :create] do
    resources :favourites, only: [:create, :destroy]
  end

  devise_for :users,
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  get 'users/dashboard', to: 'users#dashboard'


end

app/models/event.rb
class Event < ApplicationRecord
  validates :name, :start_date, presence: true
  # geocoded_by :location
  # after_validation :geocode, if: :will_save_change_to_location?
end

app/controllers/events_controller.rb
require 'open-uri'
require 'json'
require 'net/http'
require 'httparty'

class EventsController < ApplicationController
  def parse_eventbrite(location, categories = nil, start_date = nil, end_date = nil)
    @events = []
    if start_date.present? && end_date.present?
      url = "https://www.eventbriteapi.com/v3/events/search?location.address=#{location}&location.within=50km&categories=#{categories}&start_date.range_start=#{start_date+"T00:00:00"}&start_date.range_end=#{end_date+"T00:00:00"}&expand=venue&token={ENV["EVENTBRITE_API"]}"
    else
      url = "https://www.eventbriteapi.com/v3/events/search?location.address=#{location}&location.within=50km&categories=#{categories}&expand=venue&token={ENV["EVENTBRITE_API"]}"
    end
    html_file = open(url).read
    html_doc = JSON.parse(html_file)
    html_doc["events"].each do |event|
      if event["venue"]["city"] =! nil
        photo = event["logo"]["original"]["url"] if event["logo"].present?
        @events << Event.new(name: event["name"]["text"], description: event["description"]["text"], latitude: event["venue"]["latitude"], longitude: event["venue"]["longitude"], start_date: event["start"]["local"], end_date: event["end"]["local"], url: event["url"], category: find_eventbrite_category_name(event["category_id"].to_i), photo: photo)
      end
    end
    @events
  end

  def geteventfulevents(location, categories = nil, start_date = nil, end_date = nil)
    @events = []
    if start_date.present? && end_date.present?
      url = "http://api.eventful.com/json/events/search?q=#{find_eventbrite_category_name(categories)}&location=#{location}&date=#{start_date+"00-"+end_date+"00"}&app_key=f672q2vdWWFJVGmq"
    elsif categories.present?
      url = "http://api.eventful.com/json/events/search?q=#{find_eventbrite_category_name(categories)}&location=#{location}&date=Future&app_key={ENV["EVENTFUL_API"]}"
    else
      url = "http://api.eventful.com/json/events/search?q=&location=#{location}&date=Future&app_key=f672q2vdWWFJVGmq"
    end
    response = HTTParty.get(url)
    x = JSON.parse(response)
    @category_count = x["total_items"].to_i
    print(@category_count)
    #if x["events"] =! "null"
      x["events"]["event"].each do |event|
        photo = event["image"]["url"] if event["image"].present?
        @events << Event.new(name: event["title"], description: event["description"], latitude: event["latitude"], longitude: event["longitude"], start_date: event["start_time"], end_date: event["stop_time"], url: event["url"], photo: photo)
      end
    #end
    @events
  end

  def index
    @categories = [
      {id: 101, name: "Business"},
      {id: 102, name: "Science & Tech"},
      {id: 103, name: "Music"},
      {id: 104, name: "Film & Media"},
      {id: 105, name: "Arts"},
      {id: 106, name: "Fashion"},
      {id: 107, name: "Health"},
      {id: 108, name: "Sports & Fitness"},
      {id: 109, name: "Travel & Outdoor"},
      {id: 110, name: "Food & Drink"},
      {id: 111, name: "Charity & Causes"},
      {id: 112, name: "Government"},
      {id: 113, name: "Community"},
      {id: 114, name: "Spirituality"},
      {id: 115, name: "Family & Education"},
      {id: 116, name: "Holiday"},
      {id: 117, name: "Home & Lifestyle"},
      {id: 118, name: "Auto, Boat & Air"},
      {id: 119, name: "Hobbies"},
      {id: 120, name: "School Activities"},
      {id: 121, name: "Other"}
    ]
    @events = parse_using_params.uniq{|x| x.name}
      @markers = @events.map do |event|
        {
          lat: event.latitude,
          lng: event.longitude,
          infoWindow: render_to_string(partial: "info_window", locals: { event: event })
        }
      end
    @event = Event.new
  end

  def create
    @event = Event.new(event_params)
    @event.description = @event.description.gsub(/\n+/, '').gsub(/\r+/, '')
    @event.save
    @favourite = Favourite.new(event_name: @event.name, event_id: @event.id, user: current_user)
    @favourite.save
    respond_to do |format|
      format.html { redirect_to events_path }
      format.js
    end
  end

  def show
    @event = Event.find(params[:id])
  end

  private

  def event_params
    params.require(:event).permit(:name, :location, :start_date, :end_date, :start_time, :end_time, :price, :url, :photo, :category, :description, :latitude, :longitude)
  end

  def parse_using_params #removed eventbrite api call
    if params[:location].present? && params[:categories].present? && params[:start_date].present? && params[:end_date].present?
      @events = geteventfulevents(params[:location], params[:categories], params[:start_date], params[:end_date])
    elsif params[:location].present? && params[:categories].present?
      @events = geteventfulevents(params[:location], params[:categories])
    elsif params[:location].present?
      @events = geteventfulevents(params[:location])
    else
      params[:location] = "London"
      @events = geteventfulevents(params[:location])
    end
    return @events
  end
=begin
  def parse_using_params #original code
    if params[:location].present? && params[:categories].present? && params[:start_date].present? && params[:end_date].present?
      @events = parse_eventbrite(params[:location], params[:categories], params[:start_date], params[:end_date]) + geteventfulevents(params[:location], params[:categories], params[:start_date], params[:end_date])
    elsif params[:location].present? && params[:categories].present?
      @events = parse_eventbrite(params[:location], params[:categories]) + geteventfulevents(params[:location], params[:categories])
    elsif params[:location].present?
      @events = parse_eventbrite(params[:location]) + geteventfulevents(params[:location])
    else
      params[:location] = "London"
      @events = parse_eventbrite(params[:location]) + geteventfulevents(params[:location])
    end
    return @events
  end
=end
  def find_eventbrite_category_name(category_id)
    @categories = [
      {id: 101, name: "Business"},
      {id: 102, name: "Science & Tech"},
      {id: 103, name: "Music"},
      {id: 104, name: "Film & Media"},
      {id: 105, name: "Arts"},
      {id: 106, name: "Fashion"},
      {id: 107, name: "Health"},
      {id: 108, name: "Sports & Fitness"},
      {id: 109, name: "Travel & Outdoor"},
      {id: 110, name: "Food & Drink"},
      {id: 111, name: "Charity & Causes"},
      {id: 112, name: "Government"},
      {id: 113, name: "Community"},
      {id: 114, name: "Spirituality"},
      {id: 115, name: "Family & Education"},
      {id: 116, name: "Holiday"},
      {id: 117, name: "Home & Lifestyle"},
      {id: 118, name: "Auto, Boat & Air"},
      {id: 119, name: "Hobbies"},
      {id: 120, name: "School Activities"},
      {id: 121, name: "Other"}
    ]

    @categories.each do |category|
      if category[:id] == category_id
        @cat_name = category[:name]
      end
    end
    return @categories
  end
end

app/views/events/_info_window.html.erb
<a class ="popup-link-map" href="<%= event.url %>" class="href" target="_blank">
<p class=""><%= event.name %></p>
</a>

app/views/events/create.js.erb
console.log('create event and favourite');
document.getElementById("<%= @event.name.gsub(/\s+/, '').gsub(/\W+/, '') %>").innerHTML = '<%= link_to event_favourite_path(Event.find_by(name: @event.name), current_user.favourites.find_by(event_name: @event.name)), method: :delete, id: Event.find_by(name: @event.name).name.gsub(/\s+/, "").gsub(/\W+/, ""), class: "btn-red-index", remote: true do %><i class="fas fa-heart" style="font-size:20px; background: rgba(0,0,0,0);"></i><% end %>';

app/views/events/destroy.js.erb
console.log('destroy eveent');
document.getElementById("<%= @event.name.gsub(/\W+/, '') %>").innerHTML = '<i class="fa fa-heart"></i>';

app/views/events/index.html.erb
<div class="loader" style="display: none">
  <%= render "shared/loader" %>
</div>

<div class="main-container">
<div class="mapbar-div">
<%= render "shared/mapbar" %>
</div>
<div class="center-container d-flex" style="height:89vh;">
  <button id="hide_cards">-</button>
  <div class="col-3" id="cards" style="padding-left: 0px; padding-right: 0px;">
    <div id="scrollingTable" style="overflow-y:scroll">
      <% @events.each do |event| %>
        <a href="<%=event.url%>" class="href" target="_blank">
          <div class="flip-card" id="flip-card>">
            <div class="flip-card-inner">
              <div class="flip-card-front">
                <div class="card-category" style="background-image: url(<%=event.photo%>)" lat="<%=event.latitude %>" data-lat="<%=event.latitude %>"  data-lng="<%=event.longitude %>">
                </div>
               </div>
              <div class="flip-card-back">
                <ul style="list-style-type:none; padding-top: 10px;">
                  <p><strong><%= event.name %></strong></p>
                  <% if event.start_date != nil && event.end_date != nil %>
                    <% if event.start_date != event.end_date %>
                      <p>From <%= event.start_date.strftime("%A, %b %d") %> to <%= event.end_date.strftime("%A, %b %d") %></p>
                    <% else %>
                      <p> <%= event.start_date.strftime("%A, %b %d") %></p>
                    <% end %>
                  <% end %>
                  <p><%= event.location %></p>
                  <%= simple_form_for @event, remote: true do |f| %>
                    <%= f.hidden_field :name, value: event.name %>
                    <%#= f.hidden_field :location, value: event.location %>
                    <%= f.hidden_field :start_date, value: event.start_date %>
                    <%= f.hidden_field :end_date, value: event.end_date %>
                    <%#= f.hidden_field :start_time, value: event.start_time %>
                    <%#= f.hidden_field :end_time, value: event.end_time %>
                    <%= f.hidden_field :price, value: event.price %>
                    <%= f.hidden_field :latitude, value: event.latitude %>
                    <%= f.hidden_field :longitude, value: event.longitude %>
                    <%= f.hidden_field :url, value: event.url %>
                    <%= f.hidden_field :photo, value: event.photo %>
                    <%= f.hidden_field :category, value: event.category %>
                    <%= f.hidden_field :description, value: event.description %>
                    <% event_name = event.name.gsub(/\s+/, '') %>
                    <div id="link">
                      <% if current_user.favourites.find_by(event_name: event.name) %>
                        <%= link_to event_favourite_path(Event.find_by(name: event.name), current_user.favourites.find_by(event_name: event.name)), method: :delete, id: Event.find_by(name: event.name).name.gsub(/\s+/, '').gsub(/\W+/, ''), class: 'btn-red-index', remote: true do %>
                          <i class="fas fa-heart" style="font-size:20px; background: rgba(0,0,0,0);"></i>
                        <% end %>
                      <% else %>
                        <button type="submit" id="<%= event.name.gsub(/\s+/, '').gsub(/\W+/, '') %>" style="background: rgba(0,0,0,0); border:none;">
                          <i class="far fa-heart" style="color:red; font-size:20px; background: rgba(0,0,0,0);"></i>
                        </button>
                      <% end %>
                    </div>
                  <% end %>
                </ul>
              </div>
            </div>
          </div>
        </a>
      <% end %>
    </div>
  </div>
  <button id="show_cards" style="display:none;">+</button>
  <div class="map-button" style="height: 100%; width: 100%; position:relative;">
    <div id="map" data-markers="<%= @markers.to_json %>" style="height: 100%; width: 100%"></div>
    <div class="buttons" style="position: absolute; left: 10px; top: 10px;">
      <button id="toggle_markers_show" style="display:none; direction: ltr; overflow: hidden; text-align: center; height: 40px; display: table-cell; vertical-align: middle; position: relative; color: rgb(86, 86, 86); font-family: Roboto, Arial, sans-serif; user-select: none; font-size: 18px; background-color: rgb(255, 255, 255); padding: 0px 17px; border-bottom-left-radius: 2px; border-top-left-radius: 2px; background-clip: padding-box; box-shadow: rgba(0, 0, 0, 0.3) 0px 1px 4px -1px; min-width: 36px;">Toggle Markers</button>
          <button id="toggle_markers_hide" style="display:none; direction: ltr; overflow: hidden; text-align: center; height: 40px; display: table-cell; vertical-align: middle; position: relative; color: rgb(86, 86, 86); font-family: Roboto, Arial, sans-serif; user-select: none; font-size: 18px; background-color: rgb(255, 255, 255); padding: 0px 17px; border-bottom-left-radius: 2px; border-top-left-radius: 2px; background-clip: padding-box; box-shadow: rgba(0, 0, 0, 0.3) 0px 1px 4px -1px; min-width: 36px;">Toggle Markers</button>
    </div>
  </div>
<!--     <meta charset='utf-8' />
    <title>Create a heatmap layer</title>
    <meta name='viewport' content='initial-scale=1,maximum-scale=1,user-scalable=no' />
    <script src='https://api.tiles.mapbox.com/mapbox-gl-js/v1.2.0/mapbox-gl.js'></script>
    <link href='https://api.tiles.mapbox.com/mapbox-gl-js/v1.2.0/mapbox-gl.css' rel='stylesheet' /> -->
</div>
</div>

<script>
  const search = document.querySelector("#home-search")
  const loader = document.querySelector(".loader")
  const content = document.querySelector(".main-container")

  search.addEventListener("click", () => {
    content.style.display = "none"
    loader.style.display = "block"
  })
</script>

app/views/events/indexmapbox.html.erb
<%= render "shared/mapbar" %>
<div class="container">
  <%#= simple_form_for :search, url: events_path, method: :get do |f| %>
<!--     <div class="search-form-control form-group">
      <input class="form-control string required" type="text" name="location" id="search_query" />
      <button type="submit" class="btn btn-flat">
        <i class="fas fa-search"></i> Search
      </button>
    </div> -->
  <%# end %>
</div>

<div class="container d-flex" style="height:100vh;">
  <%#= render "shared/categories" %>
  <div class="card col-3">
    <div id="scrollingTable" style="overflow-y:scroll">
      <% @events.each do |event| %>
      <a href="<%=event.url%>" class="href">
        <ul style="list-style-type:none;">
          <%#= link_to "<%= event.name %><!-- <i class="far fa-heart"></i>", new_favourite_path(event) %> -->
          <p><strong><%= event.name %></strong></p><i class="far fa-heart"></i>
          <p>Start:<%= event.start_date %></p>
          <p><%= event.category %></p>
        </ul>
      </a>
      <% end %>
    </div>
  </div>
  <div
  id="map"
  style="width: 100%;
  height: 100vh;"
  data-markers="<%= @markers.to_json %>"
  data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"
  ></div>
  <meta charset='utf-8' />
  <title>Create a heatmap layer</title>
  <meta name='viewport' content='initial-scale=1,maximum-scale=1,user-scalable=no' />
  <script src='https://api.tiles.mapbox.com/mapbox-gl-js/v1.2.0/mapbox-gl.js'></script>
  <link href='https://api.tiles.mapbox.com/mapbox-gl-js/v1.2.0/mapbox-gl.css' rel='stylesheet' />
  <style>

  </style>
</div>